# roles/docker/tasks/main.yml
# Install Docker

- name: ensure dependencies are present
  apt:
    name: "{{ dep_packages }}"
    state: present
  become: yes

- name: add gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

- name: add docker repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  become: yes

- name: install docker
  apt:
    name: "{{ docker_packages }}"
    state: present
  become: yes

- name: add clicadmin user to docker system group
  user:
    name: clicadmin
    groups: docker
    append: yes
  become: yes

